/*
 * FastAPI
 * Open-source RAG Framework
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for BrainQuestionRequest
 */
public class BrainQuestionRequestTest {
    private final BrainQuestionRequest model = new BrainQuestionRequest();

    /**
     * Model tests for BrainQuestionRequest
     */
    @Test
    public void testBrainQuestionRequest() {
        // TODO: test BrainQuestionRequest
    }

    /**
     * Test the property 'question'
     */
    @Test
    public void questionTest() {
        // TODO: test question
    }

}
