/*
 * FastAPI
 * Open-source RAG Framework
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ApiBrainDefinitionEntityInputNullable;
import com.konfigthis.client.model.BrainIntegrationUpdateSettingsNullable;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for BrainUpdatableProperties
 */
public class BrainUpdatablePropertiesTest {
    private final BrainUpdatableProperties model = new BrainUpdatableProperties();

    /**
     * Model tests for BrainUpdatableProperties
     */
    @Test
    public void testBrainUpdatableProperties() {
        // TODO: test BrainUpdatableProperties
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'temperature'
     */
    @Test
    public void temperatureTest() {
        // TODO: test temperature
    }

    /**
     * Test the property 'model'
     */
    @Test
    public void modelTest() {
        // TODO: test model
    }

    /**
     * Test the property 'maxTokens'
     */
    @Test
    public void maxTokensTest() {
        // TODO: test maxTokens
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'promptId'
     */
    @Test
    public void promptIdTest() {
        // TODO: test promptId
    }

    /**
     * Test the property 'brainDefinition'
     */
    @Test
    public void brainDefinitionTest() {
        // TODO: test brainDefinition
    }

    /**
     * Test the property 'connectedBrainsIds'
     */
    @Test
    public void connectedBrainsIdsTest() {
        // TODO: test connectedBrainsIds
    }

    /**
     * Test the property 'integration'
     */
    @Test
    public void integrationTest() {
        // TODO: test integration
    }

}
