/*
 * FastAPI
 * Open-source RAG Framework
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CrawlWebsite
 */
public class CrawlWebsiteTest {
    private final CrawlWebsite model = new CrawlWebsite();

    /**
     * Model tests for CrawlWebsite
     */
    @Test
    public void testCrawlWebsite() {
        // TODO: test CrawlWebsite
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

    /**
     * Test the property 'js'
     */
    @Test
    public void jsTest() {
        // TODO: test js
    }

    /**
     * Test the property 'depth'
     */
    @Test
    public void depthTest() {
        // TODO: test depth
    }

    /**
     * Test the property 'maxPages'
     */
    @Test
    public void maxPagesTest() {
        // TODO: test maxPages
    }

    /**
     * Test the property 'maxTime'
     */
    @Test
    public void maxTimeTest() {
        // TODO: test maxTime
    }

}
