/*
 * FastAPI
 * Open-source RAG Framework
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.NotificationsStatusEnum;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for GetChatHistoryOutput
 */
public class GetChatHistoryOutputTest {
    private final GetChatHistoryOutput model = new GetChatHistoryOutput();

    /**
     * Model tests for GetChatHistoryOutput
     */
    @Test
    public void testGetChatHistoryOutput() {
        // TODO: test GetChatHistoryOutput
    }

    /**
     * Test the property 'chatId'
     */
    @Test
    public void chatIdTest() {
        // TODO: test chatId
    }

    /**
     * Test the property 'messageId'
     */
    @Test
    public void messageIdTest() {
        // TODO: test messageId
    }

    /**
     * Test the property 'userMessage'
     */
    @Test
    public void userMessageTest() {
        // TODO: test userMessage
    }

    /**
     * Test the property 'assistant'
     */
    @Test
    public void assistantTest() {
        // TODO: test assistant
    }

    /**
     * Test the property 'messageTime'
     */
    @Test
    public void messageTimeTest() {
        // TODO: test messageTime
    }

    /**
     * Test the property 'promptTitle'
     */
    @Test
    public void promptTitleTest() {
        // TODO: test promptTitle
    }

    /**
     * Test the property 'brainName'
     */
    @Test
    public void brainNameTest() {
        // TODO: test brainName
    }

    /**
     * Test the property 'brainId'
     */
    @Test
    public void brainIdTest() {
        // TODO: test brainId
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    public void metadataTest() {
        // TODO: test metadata
    }

    /**
     * Test the property 'thumbs'
     */
    @Test
    public void thumbsTest() {
        // TODO: test thumbs
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'datetime'
     */
    @Test
    public void datetimeTest() {
        // TODO: test datetime
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

    /**
     * Test the property 'action'
     */
    @Test
    public void actionTest() {
        // TODO: test action
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

}
