/*
 * FastAPI
 * Open-source RAG Framework
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.annotations.SerializedName;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for IntegrationType
 */
public class IntegrationTypeTest {
    /**
     * Model tests for IntegrationType
     */
    @Test
    public void testIntegrationType() {
        // TODO: test IntegrationType
    }

}
