/*
 * FastAPI
 * Open-source RAG Framework
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.IntegrationBrainTag;
import com.konfigthis.client.model.IntegrationType;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for IntegrationDescriptionEntity
 */
public class IntegrationDescriptionEntityTest {
    private final IntegrationDescriptionEntity model = new IntegrationDescriptionEntity();

    /**
     * Model tests for IntegrationDescriptionEntity
     */
    @Test
    public void testIntegrationDescriptionEntity() {
        // TODO: test IntegrationDescriptionEntity
    }

    /**
     * Test the property 'tags'
     */
    @Test
    public void tagsTest() {
        // TODO: test tags
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'integrationName'
     */
    @Test
    public void integrationNameTest() {
        // TODO: test integrationName
    }

    /**
     * Test the property 'integrationLogoUrl'
     */
    @Test
    public void integrationLogoUrlTest() {
        // TODO: test integrationLogoUrl
    }

    /**
     * Test the property 'connectionSettings'
     */
    @Test
    public void connectionSettingsTest() {
        // TODO: test connectionSettings
    }

    /**
     * Test the property 'integrationType'
     */
    @Test
    public void integrationTypeTest() {
        // TODO: test integrationType
    }

    /**
     * Test the property 'information'
     */
    @Test
    public void informationTest() {
        // TODO: test information
    }

    /**
     * Test the property 'maxFiles'
     */
    @Test
    public void maxFilesTest() {
        // TODO: test maxFiles
    }

    /**
     * Test the property 'allowModelChange'
     */
    @Test
    public void allowModelChangeTest() {
        // TODO: test allowModelChange
    }

    /**
     * Test the property 'integrationDisplayName'
     */
    @Test
    public void integrationDisplayNameTest() {
        // TODO: test integrationDisplayName
    }

}
