/*
 * FastAPI
 * Open-source RAG Framework
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for OnboardingStatesNullable
 */
public class OnboardingStatesNullableTest {
    private final OnboardingStatesNullable model = new OnboardingStatesNullable();

    /**
     * Model tests for OnboardingStatesNullable
     */
    @Test
    public void testOnboardingStatesNullable() {
        // TODO: test OnboardingStatesNullable
    }

    /**
     * Test the property 'onboardingA'
     */
    @Test
    public void onboardingATest() {
        // TODO: test onboardingA
    }

    /**
     * Test the property 'onboardingB1'
     */
    @Test
    public void onboardingB1Test() {
        // TODO: test onboardingB1
    }

    /**
     * Test the property 'onboardingB2'
     */
    @Test
    public void onboardingB2Test() {
        // TODO: test onboardingB2
    }

    /**
     * Test the property 'onboardingB3'
     */
    @Test
    public void onboardingB3Test() {
        // TODO: test onboardingB3
    }

}
