/*
 * FastAPI
 * Open-source RAG Framework
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ApiBrainDefinitionEntityOutputNullable;
import com.konfigthis.client.model.BrainType;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PublicBrain
 */
public class PublicBrainTest {
    private final PublicBrain model = new PublicBrain();

    /**
     * Model tests for PublicBrain
     */
    @Test
    public void testPublicBrain() {
        // TODO: test PublicBrain
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'numberOfSubscribers'
     */
    @Test
    public void numberOfSubscribersTest() {
        // TODO: test numberOfSubscribers
    }

    /**
     * Test the property 'lastUpdate'
     */
    @Test
    public void lastUpdateTest() {
        // TODO: test lastUpdate
    }

    /**
     * Test the property 'brainType'
     */
    @Test
    public void brainTypeTest() {
        // TODO: test brainType
    }

    /**
     * Test the property 'brainDefinition'
     */
    @Test
    public void brainDefinitionTest() {
        // TODO: test brainDefinition
    }

}
