/*
 * FastAPI
 * Open-source RAG Framework
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for UserIdentity
 */
public class UserIdentityTest {
    private final UserIdentity model = new UserIdentity();

    /**
     * Model tests for UserIdentity
     */
    @Test
    public void testUserIdentity() {
        // TODO: test UserIdentity
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'username'
     */
    @Test
    public void usernameTest() {
        // TODO: test username
    }

    /**
     * Test the property 'company'
     */
    @Test
    public void companyTest() {
        // TODO: test company
    }

    /**
     * Test the property 'onboarded'
     */
    @Test
    public void onboardedTest() {
        // TODO: test onboarded
    }

    /**
     * Test the property 'companySize'
     */
    @Test
    public void companySizeTest() {
        // TODO: test companySize
    }

    /**
     * Test the property 'usagePurpose'
     */
    @Test
    public void usagePurposeTest() {
        // TODO: test usagePurpose
    }

}
