/*
 * FastAPI
 * Open-source RAG Framework
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets PromptStatusEnumNullable
 */
@JsonAdapter(PromptStatusEnumNullable.Adapter.class)public enum PromptStatusEnumNullable {
  
  PRIVATE("private"),
  
  PUBLIC("public");

  private String value;

  PromptStatusEnumNullable(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static PromptStatusEnumNullable fromValue(String value) {
    for (PromptStatusEnumNullable b : PromptStatusEnumNullable.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<PromptStatusEnumNullable> {
    @Override
    public void write(final JsonWriter jsonWriter, final PromptStatusEnumNullable enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public PromptStatusEnumNullable read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return PromptStatusEnumNullable.fromValue(value);
    }
  }
}

