/*
 * FastAPI
 * Open-source RAG Framework
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * UserUpdatableProperties
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class UserUpdatableProperties {
  public static final String SERIALIZED_NAME_USERNAME = "username";
  @SerializedName(SERIALIZED_NAME_USERNAME)
  private String username;

  public static final String SERIALIZED_NAME_COMPANY = "company";
  @SerializedName(SERIALIZED_NAME_COMPANY)
  private String company;

  public static final String SERIALIZED_NAME_ONBOARDED = "onboarded";
  @SerializedName(SERIALIZED_NAME_ONBOARDED)
  private Boolean onboarded;

  public static final String SERIALIZED_NAME_COMPANY_SIZE = "company_size";
  @SerializedName(SERIALIZED_NAME_COMPANY_SIZE)
  private String companySize;

  public static final String SERIALIZED_NAME_USAGE_PURPOSE = "usage_purpose";
  @SerializedName(SERIALIZED_NAME_USAGE_PURPOSE)
  private String usagePurpose;

  public UserUpdatableProperties() {
  }

  public UserUpdatableProperties username(String username) {
    
    
    
    
    this.username = username;
    return this;
  }

   /**
   * Get username
   * @return username
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getUsername() {
    return username;
  }


  public void setUsername(String username) {
    
    
    
    this.username = username;
  }


  public UserUpdatableProperties company(String company) {
    
    
    
    
    this.company = company;
    return this;
  }

   /**
   * Get company
   * @return company
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCompany() {
    return company;
  }


  public void setCompany(String company) {
    
    
    
    this.company = company;
  }


  public UserUpdatableProperties onboarded(Boolean onboarded) {
    
    
    
    
    this.onboarded = onboarded;
    return this;
  }

   /**
   * Get onboarded
   * @return onboarded
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getOnboarded() {
    return onboarded;
  }


  public void setOnboarded(Boolean onboarded) {
    
    
    
    this.onboarded = onboarded;
  }


  public UserUpdatableProperties companySize(String companySize) {
    
    
    
    
    this.companySize = companySize;
    return this;
  }

   /**
   * Get companySize
   * @return companySize
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCompanySize() {
    return companySize;
  }


  public void setCompanySize(String companySize) {
    
    
    
    this.companySize = companySize;
  }


  public UserUpdatableProperties usagePurpose(String usagePurpose) {
    
    
    
    
    this.usagePurpose = usagePurpose;
    return this;
  }

   /**
   * Get usagePurpose
   * @return usagePurpose
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getUsagePurpose() {
    return usagePurpose;
  }


  public void setUsagePurpose(String usagePurpose) {
    
    
    
    this.usagePurpose = usagePurpose;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the UserUpdatableProperties instance itself
   */
  public UserUpdatableProperties putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserUpdatableProperties userUpdatableProperties = (UserUpdatableProperties) o;
    return Objects.equals(this.username, userUpdatableProperties.username) &&
        Objects.equals(this.company, userUpdatableProperties.company) &&
        Objects.equals(this.onboarded, userUpdatableProperties.onboarded) &&
        Objects.equals(this.companySize, userUpdatableProperties.companySize) &&
        Objects.equals(this.usagePurpose, userUpdatableProperties.usagePurpose)&&
        Objects.equals(this.additionalProperties, userUpdatableProperties.additionalProperties);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(username, company, onboarded, companySize, usagePurpose, additionalProperties);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserUpdatableProperties {\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("    company: ").append(toIndentedString(company)).append("\n");
    sb.append("    onboarded: ").append(toIndentedString(onboarded)).append("\n");
    sb.append("    companySize: ").append(toIndentedString(companySize)).append("\n");
    sb.append("    usagePurpose: ").append(toIndentedString(usagePurpose)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("username");
    openapiFields.add("company");
    openapiFields.add("onboarded");
    openapiFields.add("company_size");
    openapiFields.add("usage_purpose");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to UserUpdatableProperties
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!UserUpdatableProperties.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in UserUpdatableProperties is not found in the empty JSON string", UserUpdatableProperties.openapiRequiredFields.toString()));
        }
      }
      if (!jsonObj.get("username").isJsonNull() && (jsonObj.get("username") != null && !jsonObj.get("username").isJsonNull()) && !jsonObj.get("username").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `username` to be a primitive type in the JSON string but got `%s`", jsonObj.get("username").toString()));
      }
      if (!jsonObj.get("company").isJsonNull() && (jsonObj.get("company") != null && !jsonObj.get("company").isJsonNull()) && !jsonObj.get("company").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `company` to be a primitive type in the JSON string but got `%s`", jsonObj.get("company").toString()));
      }
      if (!jsonObj.get("company_size").isJsonNull() && (jsonObj.get("company_size") != null && !jsonObj.get("company_size").isJsonNull()) && !jsonObj.get("company_size").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `company_size` to be a primitive type in the JSON string but got `%s`", jsonObj.get("company_size").toString()));
      }
      if (!jsonObj.get("usage_purpose").isJsonNull() && (jsonObj.get("usage_purpose") != null && !jsonObj.get("usage_purpose").isJsonNull()) && !jsonObj.get("usage_purpose").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `usage_purpose` to be a primitive type in the JSON string but got `%s`", jsonObj.get("usage_purpose").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!UserUpdatableProperties.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'UserUpdatableProperties' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<UserUpdatableProperties> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(UserUpdatableProperties.class));

       return (TypeAdapter<T>) new TypeAdapter<UserUpdatableProperties>() {
           @Override
           public void write(JsonWriter out, UserUpdatableProperties value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public UserUpdatableProperties read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             UserUpdatableProperties instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of UserUpdatableProperties given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of UserUpdatableProperties
  * @throws IOException if the JSON string is invalid with respect to UserUpdatableProperties
  */
  public static UserUpdatableProperties fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, UserUpdatableProperties.class);
  }

 /**
  * Convert an instance of UserUpdatableProperties to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

