/*
 * FastAPI
 * Open-source RAG Framework
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.CrawlWebsite;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CrawlApi
 */
@Disabled
public class CrawlApiTest {

    private static CrawlApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new CrawlApi(apiClient);
    }

    /**
     * Crawl Endpoint
     *
     * Crawl a website and process the crawled data.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void websiteDataProcessorTest() throws ApiException {
        String url = null;
        UUID brainId = null;
        Boolean js = null;
        Integer depth = null;
        Integer maxPages = null;
        Integer maxTime = null;
        UUID chatId = null;
        Object response = api.websiteDataProcessor(url, brainId)
                .js(js)
                .depth(depth)
                .maxPages(maxPages)
                .maxTime(maxTime)
                .chatId(chatId)
                .execute();
        // TODO: test validations
    }

}
