/*
 * FastAPI
 * Open-source RAG Framework
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for HealthApi
 */
@Disabled
public class HealthApiTest {

    private static HealthApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new HealthApi(apiClient);
    }

    /**
     * Healthz
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void checkStatusTest() throws ApiException {
        Object response = api.checkStatus()
                .execute();
        // TODO: test validations
    }

    /**
     * Healthz
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void checkStatus_0Test() throws ApiException {
        Object response = api.checkStatus_0()
                .execute();
        // TODO: test validations
    }

    /**
     * Healthz
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void checkStatus_1Test() throws ApiException {
        Object response = api.checkStatus_1()
                .execute();
        // TODO: test validations
    }

    /**
     * Healthz
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void checkStatus_2Test() throws ApiException {
        Object response = api.checkStatus_2()
                .execute();
        // TODO: test validations
    }

}
