/*
 * FastAPI
 * Open-source RAG Framework
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for KnowledgeApi
 */
@Disabled
public class KnowledgeApiTest {

    private static KnowledgeApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new KnowledgeApi(apiClient);
    }

    /**
     * Delete Endpoint
     *
     * Delete a specific knowledge from a brain.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteSpecificBrainKnowledgeTest() throws ApiException {
        UUID knowledgeId = null;
        UUID brainId = null;
        Object response = api.deleteSpecificBrainKnowledge(knowledgeId, brainId)
                .execute();
        // TODO: test validations
    }

    /**
     * Generate Signed Url Endpoint
     *
     * Generate a signed url to download the file from storage.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void generateSignedUrlTest() throws ApiException {
        UUID knowledgeId = null;
        Object response = api.generateSignedUrl(knowledgeId)
                .execute();
        // TODO: test validations
    }

    /**
     * List Knowledge In Brain Endpoint
     *
     * Retrieve and list all the knowledge in a brain.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAllKnowledgeTest() throws ApiException {
        UUID brainId = null;
        Object response = api.getAllKnowledge(brainId)
                .execute();
        // TODO: test validations
    }

}
