/*
 * FastAPI
 * Open-source RAG Framework
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.CreatePromptProperties;
import com.konfigthis.client.model.Prompt;
import com.konfigthis.client.model.PromptNullable;
import com.konfigthis.client.model.PromptStatusEnum;
import com.konfigthis.client.model.PromptStatusEnumNullable;
import com.konfigthis.client.model.PromptUpdatableProperties;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PromptApi
 */
@Disabled
public class PromptApiTest {

    private static PromptApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new PromptApi(apiClient);
    }

    /**
     * Create Prompt Route
     *
     * Create a prompt by its id
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createPromptByIdTest() throws ApiException {
        String title = null;
        String content = null;
        PromptStatusEnum status = null;
        PromptNullable response = api.createPromptById(title, content)
                .status(status)
                .execute();
        // TODO: test validations
    }

    /**
     * Get Prompts
     *
     * Retrieve all public prompt
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAllPublicPromptsTest() throws ApiException {
        List<Prompt> response = api.getAllPublicPrompts()
                .execute();
        // TODO: test validations
    }

    /**
     * Get Prompt
     *
     * Retrieve a prompt by its id
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getByIdTest() throws ApiException {
        UUID promptId = null;
        PromptNullable response = api.getById(promptId)
                .execute();
        // TODO: test validations
    }

    /**
     * Update Prompt
     *
     * Update a prompt by its id
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateByIdTest() throws ApiException {
        UUID promptId = null;
        String title = null;
        String content = null;
        PromptStatusEnumNullable status = null;
        PromptNullable response = api.updateById(promptId)
                .title(title)
                .content(content)
                .status(status)
                .execute();
        // TODO: test validations
    }

}
